# This workflow will do publish and upload files to CloudFlare

name: .NET publish

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install wasm-tools
      run: dotnet workload install wasm-tools
    - name: Add build info
      run: |
        current_date=$(date --iso-8601=minutes)
        git_short_hash=$(git rev-parse --short HEAD)
        echo $current_date
        echo $git_short_hash
        sed -i "s/{0}/$current_date/g" src/wwwroot/index.html
        sed -i "s/{1}/$git_short_hash/g" src/wwwroot/index.html
    - name: Publish release
      run: dotnet publish src/Zen2-SMU-Checker.csproj -c Release
    - name: Remove .wasm files
      run: rm src/bin/Release/net8.0/publish/wwwroot/_framework/*.wasm
    - name: Remove .gz files
      run: rm src/bin/Release/net8.0/publish/wwwroot/_framework/*.gz
    - name: Upload to pages
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}
        command: pages publish src/bin/Release/net8.0/publish/wwwroot --project-name=zen2-smu-checker-blazor
    
